BOT_NAME = "gettyscraper"

SPIDER_MODULES = ["gettyscraper.spiders"]
NEWSPIDER_MODULE = "gettyscraper.spiders"

LOG_LEVEL = 'DEBUG'

USER_AGENT = 'gettyscraper (+http://www.hitheretourist.com)'
ROBOTSTXT_OBEY = False
CONCURRENT_REQUESTS = 40
DOWNLOAD_DELAY = 0.5
CONCURRENT_REQUESTS_PER_DOMAIN = 40
CONCURRENT_REQUESTS_PER_IP = 20
COOKIES_ENABLED = False


TELNETCONSOLE_ENABLED = False


ITEM_PIPELINES = {
    'gettyscraper.pipelines.SpiderPipeline': 300,
}

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 2
AUTOTHROTTLE_MAX_DELAY = 30
AUTOTHROTTLE_TARGET_CONCURRENCY = 10
AUTOTHROTTLE_DEBUG = False
